#!/usr/bin/env bash
# This script displays a message indefinitely then another when SIGTERM signal

sudo touch /var/run/myscript.pid
sudo echo $$ | sudo tee -a /var/run/myscript.pid
while (( 1 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command" && sudo rm "/var/run/myscript.pid" && exit' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm "/var/run/myscript.pid"' SIGQUIT
done