#!/usr/bin/env bash
# This script is displaying "Best School" 10 times and Hi after 9th iteration

i=1

while (( i <= 10 ))
do

	echo "Best School"
	if (( i == 9 ))
	then
		echo "Hi"
	fi
	(( i++))
done